{{- if .Values.nebariapp.serve.enabled -}}
# NebariApp for Ray Serve endpoint
{{ include "nebari-app.nebariApp" (dict
    "metadata" (dict
      "name"      (include "nebari-rayserve.fullname" .)
      "namespace" .Release.Namespace
      "labels"    (include "nebari-rayserve.labels" . | fromYaml)
    )
    "spec"   (omit .Values.nebariapp.serve "enabled")
    "tplCtx" .
) -}}
{{- end }}
---
{{- if .Values.nebariapp.dashboard.enabled -}}
# NebariApp for Ray Dashboard
{{ include "nebari-app.nebariApp" (dict
    "metadata" (dict
      "name"      (printf "%s-dashboard" (include "nebari-rayserve.fullname" .))
      "namespace" .Release.Namespace
      "labels"    (include "nebari-rayserve.labels" . | fromYaml)
    )
    "spec"   (omit .Values.nebariapp.dashboard "enabled")
    "tplCtx" .
) -}}
{{- end }}
