{{- if hasKey .Values.nebariapp.enabled -}}
{{- fail "nebariapp.enabled was removed in version 0.5.0. Set nebariapp.serve.enabled and nebariapp.dashboard.enabled instead." -}}
{{- end -}}

{{- if hasKey .Values.nebariapp.hostname -}}
{{- fail "nebariapp.hostname was removed in version 0.5.0. Set nebariapp.serve.hostname instead." -}}
{{- end -}}

{{- if hasKey .Values.nebariapp.service -}}
{{- fail "nebariapp.service was removed in version 0.5.0. Set nebariapp.serve.service.{name,port} and nebariapp.dashboard.service.{name,port} instead." -}}
{{- end -}}

{{- if hasKey .Values.nebariapp.auth -}}
{{- fail "nebariapp.auth was removed in version 0.5.0. Set nebariapp.serve.auth and nebariapp.dashboard.auth instead." -}}
{{- end -}}

{{- if hasKey .Values.nebariapp.gateway -}}
{{- fail "nebariapp.gateway was removed in version 0.5.0. Set nebariapp.serve.gateway and nebariapp.dashboard.gateway instead." -}}
{{- end -}}

{{- if .Values.nebariapp.serve.enabled -}}
# NebariApp for Ray Serve endpoint
{{ include "nebari-app.nebariApp" (dict
    "metadata" (dict
      "name"      (include "nebari-rayserve.fullname" .)
      "namespace" .Release.Namespace
      "labels"    (include "nebari-rayserve.labels" . | fromYaml)
    )
    "spec"   (omit .Values.nebariapp.serve "enabled")
    "tplCtx" .
) -}}
{{- end }}
---
{{- if .Values.nebariapp.dashboard.enabled -}}
# NebariApp for Ray Dashboard
{{ include "nebari-app.nebariApp" (dict
    "metadata" (dict
      "name"      (printf "%s-dashboard" (include "nebari-rayserve.fullname" .))
      "namespace" .Release.Namespace
      "labels"    (include "nebari-rayserve.labels" . | fromYaml)
    )
    "spec"   (omit .Values.nebariapp.dashboard "enabled")
    "tplCtx" .
) -}}
{{- end }}
