// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generated from the docs/ directory. Order is controlled by
  // each file's `sidebar_position` frontmatter (index.md = 1,
  // using-ray-serve.md = 2).
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
